App2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.animal.urls', namespace='animal')),
    path('pessoa/', include('apps.pessoa.urls', namespace='pessoa')),    
]

apps/animal/urls.py
from django.urls import path
from .views import home, about
app_name = 'animal'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about')
]

apps/pessoa/urls.py
from django.urls import path
from .views import contacts
app_name = 'pessoa'

urlpatterns = [
    path('', contacts, name='contacts')
]

apps/animal/models.py
from django.db import models

# Create your models here.
class Animal(models.Model):
    nome = models.CharField(max_length=50)
    especie = models.CharField(max_length=20)
    idade = models.IntegerField()

    def __str__(self):
        return f"Nome: {self.nome} ({self.especie})"

apps/pessoa/models.py
from django.db import models

# Create your models here.
class Pessoa(models.Model):
    nome = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    idade = models.IntegerField()

    def __str__(self):
       return f"Nome: {self.nome} ({self.sexo})"

apps/animal/views.py
from django.shortcuts import render

# Create your views here.
#apresentação da página estática
def home(request):
    return render(request, 'animal/home.html')

def about(request):
    return render(request, 'animal/about.html')

apps/pessoa/views.py
from django.shortcuts import render

# Create your views here.
def contacts(request):
    return render(request, 'pessoa/contacts.html')

# def about(request):
#     return render(request, 'animal/about.html')

apps/animal/templates/animal/about.html
{% extends "base.html" %}

{% block content %}
<p>TESTE ABOUT</p>
{% endblock %}

apps/animal/templates/animal/home.html
{% extends "base.html" %}

{% block content %}
<p>TESTE HOME</p>
{% endblock %}

apps/pessoa/templates/pessoa/contacts.html
{% extends "base.html" %}

{% block content %}
<p> contacts</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">



    <title>Document</title>
    <style>
        body { background-color: #a6cec1 ;};
        .btn-outline-success:hover{background-color: antiquewhite };

    </style>

</head>
<body>
    <nav class="navbar  navbar-expand-lg "  style="background-color: #ffd454;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">JaciDiniz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'animal:home' %}">Início</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'animal:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'pessoa:contacts' %}">Contacts</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="O que você procura?" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Pesquisar</button>
      </form>
    </div>
  </div>
</nav>
  <div style="padding-top: 20px;" class="container">
    {% block content %} {% endblock %}
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">



    <title>Document</title>
    <style>
        body { background-color: #a6cec1 ;};
        .btn-outline-success:hover{background-color: antiquewhite };

    </style>

</head>
<body>
    <nav class="navbar  navbar-expand-lg "  style="background-color: #ffd454;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">JaciDiniz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Início</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Links</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ações
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled"></a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="O que você procura?" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Pesquisar</button>
      </form>
    </div>
  </div>
</nav>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

</body>
</html>